### ISSUE TITLE
Modelo de Secciones

### ISSUE THREAD

**Issue by djdnl13** [IngSoft2CMS/CMS#18]
En este Issue se procederá a crear las secciones… LOS DOS GRUPOS DEBEN TRABAJAR ESTE ISSUE.

Los conceptos estan definidos en: https://github.com/IngSoft2CMS/CMS/wiki/Conceptos-del-CMS

**Comment by rdelgador** [comment]
Una consulta, ¿las diferentes secciones son solo según el tipo de contenido?

**Comment by djdnl13** [comment]
Si, solo por ese tipo.

Las secciones son para mantener una buena presentación de los contenidos, como un sistema de categorías.
